import { validDeVat } from "../tax-numbers";
import { box, dayOfMonthAfter, manualBox, nilRate, rate } from "./helpers";
import type { Jurisdiction } from "./types";

export const DE: Jurisdiction = {
  code: "DE",
  name: "Deutschland",
  flag: "🇩🇪",
  currency: "EUR",
  locale: "de-DE",
  chartLanguage: "de",
  taxName: "USt",
  taxAuthority: "Finanzamt (ELSTER)",
  taxAuthorityUrl: "https://www.elster.de/",
  taxNumber: {
    label: "USt-IdNr. oder Steuernummer",
    placeholder: "DE123456789",
    validate: validDeVat,
    hint: "DE + 9 Ziffern (Prüfziffer wird geprüft) oder Ihre Steuernummer.",
  },
  registrationThreshold: { amount: 25_000, currency: "EUR", label: "Kleinunternehmer: Vorjahresumsatz (§ 19 UStG)" },
  defaultRegistered: true,
  pricesIncludeTax: true,
  fiscalYearStart: { month: 1, day: 1 },
  filing: { frequencies: ["quarterly", "monthly", "annual"], default: "quarterly", defaultAnchorMonth: 1 },
  bases: [
    { id: "soll", label: "Sollversteuerung (vereinbarte Entgelte)", sales: "accrual", purchases: "accrual" },
    { id: "ist", label: "Istversteuerung (vereinnahmte Entgelte)", sales: "cash", purchases: "accrual", hint: "Auf Antrag bei Vorjahresumsatz bis 800.000 €. Vorsteuer weiterhin bei Rechnungseingang." },
  ],
  taxRates: [
    rate({ code: "USt19", name: "Umsatzsteuer 19 %", rateBp: 1900, appliesTo: "sales", category: "standard", componentName: "USt" }),
    rate({ code: "USt7", name: "Umsatzsteuer 7 %", rateBp: 700, appliesTo: "sales", category: "reduced", componentName: "USt", salesKey: "tax_collected_2", purchaseKey: "tax_paid_2" }),
    nilRate("STFREI", "Steuerfreie Umsätze (§ 4 UStG)", "exempt", "sales"),
    nilRate("EXPORT", "Ausfuhrlieferungen (steuerfrei)", "export", "sales"),
    nilRate("NSTB", "Nicht steuerbar", "out_of_scope"),
    rate({ code: "VSt19", name: "Vorsteuer 19 %", rateBp: 1900, appliesTo: "purchases", category: "standard", componentName: "USt" }),
    rate({ code: "VSt7", name: "Vorsteuer 7 %", rateBp: 700, appliesTo: "purchases", category: "reduced", componentName: "USt", salesKey: "tax_collected_2", purchaseKey: "tax_paid_2" }),
    nilRate("KEINE-VSt", "Ohne Vorsteuer", "exempt", "purchases"),
  ],
  defaultSalesCode: "USt19",
  defaultPurchaseCode: "VSt19",
  zeroSalesCode: "EXPORT",
  exemptSalesCode: "STFREI",
  exemptPurchaseCode: "KEINE-VSt",
  separateTaxAccounts: true,
  chartTerms: {
    taxOutput: "Umsatzsteuer 19 %",
    taxInput: "Abziehbare Vorsteuer 19 %",
    taxOutput2: "Umsatzsteuer 7 %",
    taxInput2: "Abziehbare Vorsteuer 7 %",
    taxSettlement: "Umsatzsteuer-Vorauszahlungen",
    payrollTax: "Verbindlichkeiten Lohn- und Kirchensteuer",
    retirement: "Gesetzliche soziale Aufwendungen",
    retirementPayable: "Verbindlichkeiten soziale Sicherheit",
    musicLicensing: "GEMA- und GVL-Gebühren",
  },
  returnForm: {
    code: "UStVA",
    name: "Umsatzsteuer-Voranmeldung",
    authority: "Finanzamt",
    authorityUrl: "https://www.elster.de/eportal/formulare-leistungen/alleformulare/ustva",
    boxes: [
      box("81", "Steuerpflichtige Umsätze 19 % (Bemessungsgrundlage)", (q) => q.netAtRate("sales", 1900), { section: "Lieferungen und sonstige Leistungen" }),
      box("81-St", "Steuer zu Kz. 81", (q) => q.taxAtRate("sales", 1900)),
      box("86", "Steuerpflichtige Umsätze 7 % (Bemessungsgrundlage)", (q) => q.netAtRate("sales", 700)),
      box("86-St", "Steuer zu Kz. 86", (q) => q.taxAtRate("sales", 700)),
      box("48", "Steuerfreie Umsätze ohne Vorsteuerabzug", (q) => q.net("sales", ["exempt"])),
      box("43", "Steuerfreie Umsätze mit Vorsteuerabzug (u. a. Ausfuhren)", (q) => q.net("sales", ["export", "zero"])),
      manualBox("41", "Innergemeinschaftliche Lieferungen"),
      box("66", "Vorsteuerbeträge aus Rechnungen von anderen Unternehmern", (q) => q.tax("purchases"), { section: "Abziehbare Vorsteuerbeträge" }),
      box("83", "Verbleibende Umsatzsteuer-Vorauszahlung / Überschuss (−)", (q) => q.box("81-St") + q.box("86-St") - q.box("66"), { total: true }),
    ],
    net: (q) => q.box("83"),
    dueDate: (periodEnd) => dayOfMonthAfter(periodEnd, 1, 10),
    notes: ["Mit Dauerfristverlängerung verlängert sich die Frist um einen Monat."],
  },
  notes: [
    "Tanzunterricht kann nach § 4 Nr. 21 UStG umsatzsteuerfrei sein, wenn eine Bescheinigung der zuständigen Landesbehörde vorliegt. Dann den Unterricht auf STFREI umstellen.",
    "Kleinunternehmer (§ 19 UStG, Vorjahresumsatz bis 25.000 €) weisen keine Umsatzsteuer aus. Wählen Sie dann „nicht umsatzsteuerpflichtig“.",
    "Die Voranmeldung wird hier vorbereitet; die Übermittlung erfolgt über ELSTER. Ein DATEV-Export ist noch nicht verfügbar.",
  ],
  reviewedAt: "2026-10-01",
};
