import { validFrVat } from "../tax-numbers";
import { box, dayOfMonthAfter, nilRate, rate } from "./helpers";
import type { Jurisdiction } from "./types";

export const FR: Jurisdiction = {
  code: "FR",
  name: "France",
  flag: "🇫🇷",
  currency: "EUR",
  locale: "fr-FR",
  chartLanguage: "fr",
  taxName: "TVA",
  taxAuthority: "Direction générale des Finances publiques (DGFiP)",
  taxAuthorityUrl: "https://www.impots.gouv.fr/professionnel/la-tva",
  taxNumber: {
    label: "N° de TVA intracommunautaire ou SIREN",
    placeholder: "FR 40 303265045",
    validate: validFrVat,
    hint: "FR + clé + SIREN (la clé numérique est vérifiée), ou SIREN seul.",
  },
  defaultRegistered: true,
  pricesIncludeTax: true,
  fiscalYearStart: { month: 1, day: 1 },
  filing: { frequencies: ["monthly", "quarterly", "annual"], default: "monthly", defaultAnchorMonth: 1 },
  bases: [
    { id: "encaissements", label: "TVA sur les encaissements (prestations de services)", sales: "cash", purchases: "cash", hint: "Régime par défaut pour les prestations de services." },
    { id: "debits", label: "TVA sur les débits (option)", sales: "accrual", purchases: "accrual" },
  ],
  taxRates: [
    rate({ code: "TVA20", name: "TVA collectée 20 %", rateBp: 2000, appliesTo: "sales", category: "standard", componentName: "TVA" }),
    rate({ code: "TVA10", name: "TVA collectée 10 %", rateBp: 1000, appliesTo: "sales", category: "reduced", componentName: "TVA" }),
    rate({ code: "TVA5.5", name: "TVA collectée 5,5 %", rateBp: 550, appliesTo: "sales", category: "second_reduced", componentName: "TVA" }),
    rate({ code: "TVA2.1", name: "TVA collectée 2,1 %", rateBp: 210, appliesTo: "sales", category: "super_reduced", componentName: "TVA" }),
    nilRate("EXO", "Opérations exonérées", "exempt", "sales"),
    nilRate("EXPORT", "Exportations hors UE", "export", "sales"),
    nilRate("HC", "Hors champ", "out_of_scope"),
    rate({ code: "TVA20-D", name: "TVA déductible 20 %", rateBp: 2000, appliesTo: "purchases", category: "standard", componentName: "TVA" }),
    rate({ code: "TVA10-D", name: "TVA déductible 10 %", rateBp: 1000, appliesTo: "purchases", category: "reduced", componentName: "TVA" }),
    rate({ code: "TVA5.5-D", name: "TVA déductible 5,5 %", rateBp: 550, appliesTo: "purchases", category: "second_reduced", componentName: "TVA" }),
    nilRate("SANS-D", "Sans TVA déductible", "exempt", "purchases"),
  ],
  defaultSalesCode: "TVA20",
  defaultPurchaseCode: "TVA20-D",
  zeroSalesCode: "EXPORT",
  exemptSalesCode: "EXO",
  exemptPurchaseCode: "SANS-D",
  separateTaxAccounts: true,
  chartTerms: {
    taxOutput: "TVA collectée",
    taxInput: "TVA déductible sur biens et services",
    taxSettlement: "TVA à décaisser",
    payrollTax: "Sécurité sociale (URSSAF)",
    retirement: "Charges de sécurité sociale et de prévoyance",
    retirementPayable: "Autres organismes sociaux",
    musicLicensing: "Droits SACEM / SPRE",
  },
  returnForm: {
    code: "CA3",
    name: "Déclaration de TVA (CA3)",
    authority: "DGFiP",
    authorityUrl: "https://www.impots.gouv.fr/professionnel/questions/comment-declarer-la-tva",
    boxes: [
      box("A1", "Ventes, prestations de services (montant HT)", (q) => q.net("sales", ["standard", "reduced", "second_reduced", "super_reduced"]), { section: "A. Montant des opérations réalisées" }),
      box("E1", "Exportations hors UE", (q) => q.net("sales", ["export"])),
      box("E2", "Autres opérations non imposables", (q) => q.net("sales", ["exempt", "zero"])),
      box("08", "Taux normal 20 % — base hors taxe", (q) => q.netAtRate("sales", 2000), { section: "B. Décompte de la TVA à payer" }),
      box("08-T", "Taux normal 20 % — taxe due", (q) => q.taxAtRate("sales", 2000)),
      box("9B", "Taux réduit 10 % — base hors taxe", (q) => q.netAtRate("sales", 1000)),
      box("9B-T", "Taux réduit 10 % — taxe due", (q) => q.taxAtRate("sales", 1000)),
      box("09", "Taux réduit 5,5 % — base hors taxe", (q) => q.netAtRate("sales", 550)),
      box("09-T", "Taux réduit 5,5 % — taxe due", (q) => q.taxAtRate("sales", 550)),
      box("16", "Total de la TVA brute due", (q) => q.tax("sales"), { total: true }),
      box("20", "Autres biens et services (TVA déductible)", (q) => q.tax("purchases")),
      box("23", "Total TVA déductible", (q) => q.box("20"), { total: true }),
      box("28", "TVA nette due (ligne 16 − ligne 23)", (q) => Math.max(q.box("16") - q.box("23"), 0), { total: true }),
      box("25", "Crédit de TVA (ligne 23 − ligne 16)", (q) => Math.max(q.box("23") - q.box("16"), 0), { total: true }),
    ],
    net: (q) => q.box("16") - q.box("23"),
    dueDate: (periodEnd) => dayOfMonthAfter(periodEnd, 1, 19),
    notes: ["La date limite exacte (entre le 15 et le 24) dépend de votre SIREN et de votre régime. Au régime simplifié, la CA12 annuelle reprend les mêmes montants."],
  },
  notes: [
    "Franchise en base (art. 293 B du CGI) : en dessous du seuil, vous ne facturez pas de TVA. Choisissez alors « non assujetti ».",
    "L'enseignement dispensé par certains organismes ou par des personnes physiques peut être exonéré (art. 261-4-4° du CGI). Vérifiez avant d'appliquer la TVA aux cours.",
    "Le fichier des écritures comptables (FEC) peut être exporté depuis Rapports → Journal. La facturation électronique obligatoire (réforme 2026-2027) n'est pas encore prise en charge.",
  ],
  reviewedAt: "2026-10-01",
};
