import { validGbVat } from "../tax-numbers";
import { IN_SCOPE, box, manualBox, monthsAndDaysAfter, nilRate, rate } from "./helpers";
import type { Jurisdiction } from "./types";

export const GB: Jurisdiction = {
  code: "GB",
  name: "United Kingdom",
  flag: "🇬🇧",
  currency: "GBP",
  locale: "en-GB",
  chartLanguage: "en",
  taxName: "VAT",
  taxAuthority: "HM Revenue & Customs (HMRC)",
  taxAuthorityUrl: "https://www.gov.uk/vat-registration",
  taxNumber: {
    label: "VAT registration number",
    placeholder: "GB 123 4567 89",
    validate: validGbVat,
    hint: "GB followed by 9 digits. Checked with HMRC's mod-97 rule.",
  },
  registrationThreshold: { amount: 90_000, currency: "GBP", label: "Taxable turnover over 12 months" },
  defaultRegistered: true,
  pricesIncludeTax: true,
  fiscalYearStart: { month: 4, day: 1 },
  filing: { frequencies: ["quarterly", "monthly", "annual"], default: "quarterly", defaultAnchorMonth: 1 },
  bases: [
    { id: "standard", label: "Standard accounting (invoice basis)", sales: "accrual", purchases: "accrual" },
    { id: "cash", label: "Cash accounting scheme", sales: "cash", purchases: "cash", hint: "Available when taxable turnover is £1.35m or less." },
  ],
  taxRates: [
    rate({ code: "VAT20", name: "20% (VAT on income)", rateBp: 2000, appliesTo: "sales", category: "standard", componentName: "VAT" }),
    rate({ code: "VAT5", name: "5% (VAT on income)", rateBp: 500, appliesTo: "sales", category: "reduced", componentName: "VAT" }),
    nilRate("ZERO", "Zero rated income", "zero", "sales"),
    nilRate("EXEMPT", "Exempt income", "exempt", "sales"),
    rate({ code: "VAT20-P", name: "20% (VAT on expenses)", rateBp: 2000, appliesTo: "purchases", category: "standard", componentName: "VAT" }),
    rate({ code: "VAT5-P", name: "5% (VAT on expenses)", rateBp: 500, appliesTo: "purchases", category: "reduced", componentName: "VAT" }),
    nilRate("ZERO-P", "Zero rated expenses", "zero", "purchases"),
    nilRate("EXEMPT-P", "Exempt expenses", "exempt", "purchases"),
    nilRate("NOVAT", "No VAT (outside the scope)", "out_of_scope"),
  ],
  defaultSalesCode: "VAT20",
  defaultPurchaseCode: "VAT20-P",
  zeroSalesCode: "ZERO",
  exemptSalesCode: "EXEMPT",
  exemptPurchaseCode: "EXEMPT-P",
  separateTaxAccounts: false,
  chartTerms: {
    taxOutput: "VAT",
    payrollTax: "PAYE & NIC payable",
    retirement: "Workplace pension contributions",
    retirementPayable: "Pension contributions payable",
    musicLicensing: "PPL PRS music licence",
  },
  returnForm: {
    code: "VAT100",
    name: "VAT return (VAT100)",
    authority: "HMRC",
    authorityUrl: "https://www.gov.uk/submit-vat-return",
    boxes: [
      box("1", "VAT due on sales and other outputs", (q) => q.tax("sales")),
      manualBox("2", "VAT due on acquisitions of goods made in Northern Ireland from EU member states"),
      box("3", "Total VAT due (Box 1 + Box 2)", (q) => q.box("1") + q.box("2"), { total: true }),
      box("4", "VAT reclaimed on purchases and other inputs", (q) => q.tax("purchases")),
      box("5", "Net VAT to pay to HMRC or reclaim (Box 3 − Box 4)", (q) => q.box("3") - q.box("4"), { total: true }),
      box("6", "Total value of sales and all other outputs, excluding VAT", (q) => q.net("sales", IN_SCOPE)),
      box("7", "Total value of purchases and all other inputs, excluding VAT", (q) => q.net("purchases", IN_SCOPE)),
      manualBox("8", "Total value of goods supplied from Northern Ireland to EU member states, excluding VAT"),
      manualBox("9", "Total value of goods acquired in Northern Ireland from EU member states, excluding VAT"),
    ],
    net: (q) => q.box("5"),
    dueDate: (periodEnd) => monthsAndDaysAfter(periodEnd, 1, 7),
    notes: [
      "HMRC wants boxes 6–9 in whole pounds; round down when you enter them.",
      "Making Tax Digital: VAT returns must be submitted from MTD-compatible software. Olune Books prepares the figures but can't submit to HMRC yet, so use bridging software or your accountant.",
    ],
  },
  notes: [
    "Registration is compulsory once taxable turnover passes £90,000 in a rolling 12 months.",
    "Private tuition from a sole trader in a subject ordinarily taught in schools can be VAT-exempt. Check HMRC VAT Notice 701/30 before charging VAT on lessons.",
  ],
  reviewedAt: "2026-10-01",
};
