import { validIeVat } from "../tax-numbers";
import { box, dayOfMonthAfter, manualBox, nilRate, rate } from "./helpers";
import type { Jurisdiction } from "./types";

export const IE: Jurisdiction = {
  code: "IE",
  name: "Ireland",
  flag: "🇮🇪",
  currency: "EUR",
  locale: "en-IE",
  chartLanguage: "en",
  taxName: "VAT",
  taxAuthority: "Revenue (Office of the Revenue Commissioners)",
  taxAuthorityUrl: "https://www.revenue.ie/en/vat/index.aspx",
  taxNumber: {
    label: "VAT number",
    placeholder: "IE 1234567 FA",
    validate: validIeVat,
    hint: "7 digits and one or two letters. The check letter is verified.",
  },
  registrationThreshold: { amount: 42_500, currency: "EUR", label: "Supplies of services per year" },
  defaultRegistered: true,
  pricesIncludeTax: true,
  fiscalYearStart: { month: 1, day: 1 },
  filing: { frequencies: ["bimonthly", "six_monthly", "annual"], default: "bimonthly", defaultAnchorMonth: 1 },
  bases: [
    { id: "invoice", label: "Invoice basis", sales: "accrual", purchases: "accrual" },
    { id: "cash", label: "Cash receipts basis (moneys received)", sales: "cash", purchases: "accrual", hint: "Turnover under €2m. VAT on purchases is still claimed on invoice." },
  ],
  taxRates: [
    rate({ code: "VAT23", name: "23% standard rate", rateBp: 2300, appliesTo: "sales", category: "standard", componentName: "VAT" }),
    rate({ code: "VAT13.5", name: "13.5% reduced rate", rateBp: 1350, appliesTo: "sales", category: "reduced", componentName: "VAT" }),
    rate({ code: "VAT9", name: "9% second reduced rate", rateBp: 900, appliesTo: "sales", category: "second_reduced", componentName: "VAT" }),
    nilRate("ZERO", "Zero rated", "zero", "sales"),
    nilRate("EXEMPT", "Exempt", "exempt", "sales"),
    rate({ code: "VAT23-P", name: "23% on purchases", rateBp: 2300, appliesTo: "purchases", category: "standard", componentName: "VAT" }),
    rate({ code: "VAT13.5-P", name: "13.5% on purchases", rateBp: 1350, appliesTo: "purchases", category: "reduced", componentName: "VAT" }),
    rate({ code: "VAT9-P", name: "9% on purchases", rateBp: 900, appliesTo: "purchases", category: "second_reduced", componentName: "VAT" }),
    nilRate("ZERO-P", "Zero rated purchases", "zero", "purchases"),
    nilRate("EXEMPT-P", "Exempt purchases", "exempt", "purchases"),
    nilRate("NOVAT", "Outside the scope of VAT", "out_of_scope"),
  ],
  defaultSalesCode: "VAT23",
  defaultPurchaseCode: "VAT23-P",
  zeroSalesCode: "ZERO",
  exemptSalesCode: "EXEMPT",
  exemptPurchaseCode: "EXEMPT-P",
  separateTaxAccounts: false,
  chartTerms: {
    taxOutput: "VAT",
    payrollTax: "PAYE / PRSI / USC payable",
    retirement: "Employer pension contributions",
    retirementPayable: "Pension contributions payable",
    musicLicensing: "IMRO / PPI music licence",
  },
  returnForm: {
    code: "VAT3",
    name: "VAT return (VAT3)",
    authority: "Revenue",
    authorityUrl: "https://www.revenue.ie/en/vat/vat-returns/index.aspx",
    boxes: [
      box("T1", "VAT on sales", (q) => q.tax("sales")),
      box("T2", "VAT on purchases", (q) => q.tax("purchases")),
      box("T3", "Net payable (T1 − T2, if positive)", (q) => Math.max(q.box("T1") - q.box("T2"), 0), { total: true }),
      box("T4", "Net repayable (T2 − T1, if positive)", (q) => Math.max(q.box("T2") - q.box("T1"), 0), { total: true }),
      manualBox("E1", "Intra-EU supplies of goods", "Intra-EU trade"),
      manualBox("E2", "Intra-EU acquisitions of goods"),
      manualBox("ES1", "Intra-EU supplies of services"),
      manualBox("ES2", "Intra-EU acquisitions of services"),
    ],
    net: (q) => q.box("T1") - q.box("T2"),
    dueDate: (periodEnd) => dayOfMonthAfter(periodEnd, 1, 23),
    notes: ["Due on the 23rd when you file and pay through ROS, or the 19th otherwise."],
  },
  notes: [
    "Registration is required once turnover from services exceeds €42,500 in 12 months (€85,000 for goods).",
    "Some education and sporting services are VAT-exempt. Check Revenue's guidance before charging VAT on classes.",
    "The annual Return of Trading Details (RTD) isn't prepared here.",
  ],
  reviewedAt: "2026-10-01",
};
