import { validItVat } from "../tax-numbers";
import { box, dayOfMonthAfter, nilRate, rate } from "./helpers";
import type { Jurisdiction } from "./types";

export const IT: Jurisdiction = {
  code: "IT",
  name: "Italia",
  flag: "🇮🇹",
  currency: "EUR",
  locale: "it-IT",
  chartLanguage: "it",
  taxName: "IVA",
  taxAuthority: "Agenzia delle Entrate",
  taxAuthorityUrl: "https://www.agenziaentrate.gov.it/portale/web/guest/aree-tematiche/iva",
  taxNumber: {
    label: "Partita IVA",
    placeholder: "IT 12345678903",
    validate: validItVat,
    hint: "11 cifre; viene verificata la cifra di controllo.",
  },
  defaultRegistered: true,
  pricesIncludeTax: true,
  fiscalYearStart: { month: 1, day: 1 },
  filing: { frequencies: ["quarterly", "monthly"], default: "quarterly", defaultAnchorMonth: 1 },
  bases: [
    { id: "immediata", label: "Esigibilità immediata", sales: "accrual", purchases: "accrual" },
    { id: "cassa", label: "IVA per cassa (art. 32-bis)", sales: "cash", purchases: "cash", hint: "Volume d'affari fino a 2 milioni di euro." },
  ],
  taxRates: [
    rate({ code: "IVA22", name: "IVA 22%", rateBp: 2200, appliesTo: "sales", category: "standard", componentName: "IVA" }),
    rate({ code: "IVA10", name: "IVA 10%", rateBp: 1000, appliesTo: "sales", category: "reduced", componentName: "IVA" }),
    rate({ code: "IVA5", name: "IVA 5%", rateBp: 500, appliesTo: "sales", category: "second_reduced", componentName: "IVA" }),
    rate({ code: "IVA4", name: "IVA 4%", rateBp: 400, appliesTo: "sales", category: "super_reduced", componentName: "IVA" }),
    nilRate("ES10", "Esente art. 10", "exempt", "sales"),
    nilRate("NI8", "Non imponibile art. 8 (esportazioni)", "export", "sales"),
    nilRate("FC", "Fuori campo IVA", "out_of_scope"),
    rate({ code: "IVA22-A", name: "IVA 22% su acquisti", rateBp: 2200, appliesTo: "purchases", category: "standard", componentName: "IVA" }),
    rate({ code: "IVA10-A", name: "IVA 10% su acquisti", rateBp: 1000, appliesTo: "purchases", category: "reduced", componentName: "IVA" }),
    rate({ code: "IVA4-A", name: "IVA 4% su acquisti", rateBp: 400, appliesTo: "purchases", category: "super_reduced", componentName: "IVA" }),
    nilRate("ES-A", "Acquisti esenti", "exempt", "purchases"),
  ],
  defaultSalesCode: "IVA22",
  defaultPurchaseCode: "IVA22-A",
  zeroSalesCode: "NI8",
  exemptSalesCode: "ES10",
  exemptPurchaseCode: "ES-A",
  separateTaxAccounts: true,
  chartTerms: {
    taxOutput: "IVA a debito",
    taxInput: "IVA a credito",
    taxSettlement: "Erario c/IVA",
    payrollTax: "Debiti verso Erario per ritenute",
    retirement: "Contributi previdenziali (INPS)",
    retirementPayable: "Debiti verso istituti previdenziali",
    musicLicensing: "Diritti SIAE / SCF",
  },
  returnForm: {
    code: "LIPE",
    name: "Comunicazione liquidazioni periodiche IVA",
    authority: "Agenzia delle Entrate",
    authorityUrl: "https://www.agenziaentrate.gov.it/portale/web/guest/schede/comunicazioni/comunicazioni-liquidazioni-periodiche-iva",
    boxes: [
      box("VP2", "Totale operazioni attive (al netto dell'IVA)", (q) => q.net("sales", ["standard", "reduced", "second_reduced", "super_reduced", "zero", "exempt", "export"])),
      box("VP3", "Totale operazioni passive (al netto dell'IVA)", (q) => q.net("purchases", ["standard", "reduced", "second_reduced", "super_reduced", "zero", "exempt"])),
      box("VP4", "IVA esigibile", (q) => q.tax("sales")),
      box("VP5", "IVA detratta", (q) => q.tax("purchases")),
      box("VP6", "IVA dovuta (o a credito se negativa)", (q) => q.box("VP4") - q.box("VP5"), { total: true }),
    ],
    net: (q) => q.box("VP6"),
    dueDate: (periodEnd) => dayOfMonthAfter(periodEnd, 1, 16),
    notes: ["Il versamento è dovuto il 16 del mese successivo (trimestrale: 16 del secondo mese, con maggiorazione dell'1%). La LIPE trimestrale si presenta entro la fine del secondo mese."],
  },
  notes: [
    "Regime forfettario: se aderite, non addebitate IVA. Scegliete in tal caso «non soggetto IVA».",
    "Alcuni corsi di danza possono essere esenti ai sensi dell'art. 10 DPR 633/72 (es. enti riconosciuti). Verificate prima di applicare l'IVA.",
    "La fatturazione elettronica tramite SdI è obbligatoria; Olune non trasmette ancora le fatture al Sistema di Interscambio.",
  ],
  reviewedAt: "2026-10-01",
};
