import { validNlVat } from "../tax-numbers";
import { box, endOfMonthAfter, nilRate, rate } from "./helpers";
import type { Jurisdiction } from "./types";

export const NL: Jurisdiction = {
  code: "NL",
  name: "Nederland",
  flag: "🇳🇱",
  currency: "EUR",
  locale: "nl-NL",
  chartLanguage: "nl",
  taxName: "Btw",
  taxAuthority: "Belastingdienst",
  taxAuthorityUrl: "https://www.belastingdienst.nl/wps/wcm/connect/nl/btw/btw",
  taxNumber: {
    label: "Btw-identificatienummer",
    placeholder: "NL000099998B57",
    validate: validNlVat,
    hint: "NL + 9 cijfers + B + 2 cijfers. Het controlegetal wordt gecontroleerd.",
  },
  registrationThreshold: { amount: 20_000, currency: "EUR", label: "Kleineondernemersregeling (KOR): omzet per jaar" },
  defaultRegistered: true,
  pricesIncludeTax: true,
  fiscalYearStart: { month: 1, day: 1 },
  filing: { frequencies: ["quarterly", "monthly", "annual"], default: "quarterly", defaultAnchorMonth: 1 },
  bases: [
    { id: "factuur", label: "Factuurstelsel", sales: "accrual", purchases: "accrual" },
    { id: "kas", label: "Kasstelsel", sales: "cash", purchases: "cash", hint: "Alleen met toestemming van de Belastingdienst." },
  ],
  taxRates: [
    rate({ code: "BTW21", name: "Btw hoog 21%", rateBp: 2100, appliesTo: "sales", category: "standard", componentName: "Btw" }),
    rate({ code: "BTW9", name: "Btw laag 9%", rateBp: 900, appliesTo: "sales", category: "reduced", componentName: "Btw" }),
    nilRate("BTW0", "Btw 0%", "zero", "sales"),
    nilRate("VRIJ", "Vrijgesteld van btw", "exempt", "sales"),
    nilRate("EXPORT", "Leveringen buiten de EU", "export", "sales"),
    nilRate("GEEN", "Geen btw (buiten de heffing)", "out_of_scope"),
    rate({ code: "VOOR21", name: "Voorbelasting 21%", rateBp: 2100, appliesTo: "purchases", category: "standard", componentName: "Btw" }),
    rate({ code: "VOOR9", name: "Voorbelasting 9%", rateBp: 900, appliesTo: "purchases", category: "reduced", componentName: "Btw" }),
    nilRate("VRIJ-I", "Inkoop zonder btw", "exempt", "purchases"),
  ],
  defaultSalesCode: "BTW21",
  defaultPurchaseCode: "VOOR21",
  zeroSalesCode: "BTW0",
  exemptSalesCode: "VRIJ",
  exemptPurchaseCode: "VRIJ-I",
  separateTaxAccounts: true,
  chartTerms: {
    taxOutput: "Te betalen btw",
    taxInput: "Te vorderen btw (voorbelasting)",
    taxSettlement: "Af te dragen btw",
    payrollTax: "Af te dragen loonheffing",
    retirement: "Pensioenpremies",
    retirementPayable: "Te betalen pensioenpremies",
    musicLicensing: "Buma/Stemra en Sena",
  },
  returnForm: {
    code: "OB",
    name: "Btw-aangifte",
    authority: "Belastingdienst",
    authorityUrl: "https://www.belastingdienst.nl/wps/wcm/connect/nl/btw/content/btw-aangifte-doen",
    boxes: [
      box("1a", "Leveringen/diensten belast met hoog tarief — omzet", (q) => q.netAtRate("sales", 2100), { section: "1. Prestaties binnenland" }),
      box("1a-btw", "Leveringen/diensten belast met hoog tarief — btw", (q) => q.taxAtRate("sales", 2100)),
      box("1b", "Leveringen/diensten belast met laag tarief — omzet", (q) => q.netAtRate("sales", 900)),
      box("1b-btw", "Leveringen/diensten belast met laag tarief — btw", (q) => q.taxAtRate("sales", 900)),
      box("1e", "Leveringen/diensten belast met 0% of niet bij u belast", (q) => q.net("sales", ["zero"])),
      box("3a", "Leveringen naar landen buiten de EU", (q) => q.net("sales", ["export"]), { section: "3. Prestaties naar of in het buitenland" }),
      box("5a", "Verschuldigde btw", (q) => q.tax("sales"), { section: "5. Voorbelasting en totaal" }),
      box("5b", "Voorbelasting", (q) => q.tax("purchases")),
      box("5c", "Subtotaal (5a − 5b)", (q) => q.box("5a") - q.box("5b"), { total: true }),
      box("5g", "Totaal te betalen / terug te vragen", (q) => q.box("5c"), { total: true }),
    ],
    net: (q) => q.box("5g"),
    dueDate: (periodEnd) => endOfMonthAfter(periodEnd, 1),
  },
  notes: [
    "Met de kleineondernemersregeling (KOR, omzet tot €20.000) rekent u geen btw. Kies dan ‘niet btw-plichtig’.",
    "Danslessen kunnen onder voorwaarden vrijgesteld zijn (onderwijs of sport). Controleer dit voordat u btw rekent.",
  ],
  reviewedAt: "2026-10-01",
};
