import { validSgGst } from "../tax-numbers";
import { box, endOfMonthAfter, nilRate, rate } from "./helpers";
import type { Jurisdiction } from "./types";

export const SG: Jurisdiction = {
  code: "SG",
  name: "Singapore",
  flag: "🇸🇬",
  currency: "SGD",
  locale: "en-SG",
  chartLanguage: "en",
  taxName: "GST",
  taxAuthority: "Inland Revenue Authority of Singapore (IRAS)",
  taxAuthorityUrl: "https://www.iras.gov.sg/taxes/goods-services-tax-(gst)",
  taxNumber: {
    label: "GST registration number / UEN",
    placeholder: "201912345K",
    validate: validSgGst,
    hint: "Your UEN or M2- GST number. Format is checked; IRAS's register confirms it.",
  },
  registrationThreshold: { amount: 1_000_000, currency: "SGD", label: "Taxable supplies over 12 months" },
  defaultRegistered: false,
  pricesIncludeTax: true,
  fiscalYearStart: { month: 1, day: 1 },
  filing: { frequencies: ["quarterly", "monthly"], default: "quarterly", defaultAnchorMonth: 1 },
  bases: [
    { id: "invoice", label: "Invoice basis", sales: "accrual", purchases: "accrual" },
    { id: "cash", label: "Cash accounting scheme", sales: "cash", purchases: "cash", hint: "For businesses with taxable turnover up to S$1m." },
  ],
  taxRates: [
    rate({ code: "SR", name: "Standard-rated supplies (9%)", rateBp: 900, appliesTo: "sales", category: "standard", componentName: "GST" }),
    nilRate("ZR", "Zero-rated supplies", "zero", "sales"),
    nilRate("ES", "Exempt supplies", "exempt", "sales"),
    nilRate("OS", "Out-of-scope supplies", "out_of_scope"),
    rate({ code: "TX", name: "Standard-rated purchases (9%)", rateBp: 900, appliesTo: "purchases", category: "standard", componentName: "GST" }),
    rate({ code: "IM", name: "GST paid on imports (9%)", rateBp: 900, appliesTo: "purchases", category: "import", componentName: "GST" }),
    nilRate("ZP", "Zero-rated purchases", "zero", "purchases"),
    nilRate("EP", "Exempt purchases", "exempt", "purchases"),
  ],
  defaultSalesCode: "SR",
  defaultPurchaseCode: "TX",
  zeroSalesCode: "ZR",
  exemptSalesCode: "ES",
  exemptPurchaseCode: "EP",
  separateTaxAccounts: false,
  chartTerms: {
    taxOutput: "GST",
    payrollTax: "Payroll liabilities",
    retirement: "CPF employer contributions",
    retirementPayable: "CPF payable",
    musicLicensing: "COMPASS music licence",
  },
  returnForm: {
    code: "F5",
    name: "GST return (GST F5)",
    authority: "IRAS",
    authorityUrl: "https://www.iras.gov.sg/taxes/goods-services-tax-(gst)/filing-gst",
    boxes: [
      box("1", "Total value of standard-rated supplies", (q) => q.net("sales", ["standard"])),
      box("2", "Total value of zero-rated supplies", (q) => q.net("sales", ["zero", "export"])),
      box("3", "Total value of exempt supplies", (q) => q.net("sales", ["exempt"])),
      box("4", "Total value of (1) + (2) + (3)", (q) => q.box("1") + q.box("2") + q.box("3"), { total: true }),
      box("5", "Total value of taxable purchases", (q) => q.net("purchases", ["standard", "import", "zero"])),
      box("6", "Output tax due", (q) => q.tax("sales")),
      box("7", "Less: input tax and refunds claimed", (q) => q.tax("purchases")),
      box("8", "Equals: net GST to be paid to / (claimed from) IRAS", (q) => q.box("6") - q.box("7"), { total: true }),
    ],
    net: (q) => q.box("8"),
    dueDate: (periodEnd) => endOfMonthAfter(periodEnd, 1),
  },
  notes: [
    "Registration is compulsory once taxable supplies pass S$1m in a calendar year (or are expected to in the next 12 months). Most studios are below that and leave GST off.",
    "Olune Books prepares the F5 figures; you file them in myTax Portal.",
  ],
  reviewedAt: "2026-10-01",
};
