import { validZaVat } from "../tax-numbers";
import { box, endOfMonthAfter, nilRate, rate } from "./helpers";
import type { Jurisdiction } from "./types";

export const ZA: Jurisdiction = {
  code: "ZA",
  name: "South Africa",
  flag: "🇿🇦",
  currency: "ZAR",
  locale: "en-ZA",
  chartLanguage: "en",
  taxName: "VAT",
  taxAuthority: "South African Revenue Service (SARS)",
  taxAuthorityUrl: "https://www.sars.gov.za/types-of-tax/value-added-tax/",
  taxNumber: {
    label: "VAT vendor number",
    placeholder: "4123456789",
    validate: validZaVat,
    hint: "10 digits starting with 4.",
  },
  defaultRegistered: true,
  pricesIncludeTax: true,
  fiscalYearStart: { month: 3, day: 1 },
  filing: { frequencies: ["bimonthly", "monthly", "six_monthly", "annual"], default: "bimonthly", defaultAnchorMonth: 1 },
  bases: [
    { id: "invoice", label: "Invoice basis", sales: "accrual", purchases: "accrual" },
    { id: "payments", label: "Payments basis", sales: "cash", purchases: "cash", hint: "Natural persons and some others with turnover under the SARS limit." },
  ],
  taxRates: [
    rate({ code: "VAT15", name: "Standard rate (15%)", rateBp: 1500, appliesTo: "sales", category: "standard", componentName: "VAT" }),
    nilRate("ZERO", "Zero rated (excluding exports)", "zero", "sales"),
    nilRate("EXPORT", "Zero rated exports", "export", "sales"),
    nilRate("EXEMPT", "Exempt and non-supplies", "exempt", "sales"),
    rate({ code: "VAT15-P", name: "Standard rate purchases (15%)", rateBp: 1500, appliesTo: "purchases", category: "standard", componentName: "VAT" }),
    rate({ code: "CAP", name: "Capital goods (15%)", rateBp: 1500, appliesTo: "purchases", category: "capital", componentName: "VAT" }),
    nilRate("ZERO-P", "Zero rated purchases", "zero", "purchases"),
    nilRate("EXEMPT-P", "Exempt purchases", "exempt", "purchases"),
    nilRate("NOVAT", "No VAT", "out_of_scope"),
  ],
  defaultSalesCode: "VAT15",
  defaultPurchaseCode: "VAT15-P",
  zeroSalesCode: "ZERO",
  exemptSalesCode: "EXEMPT",
  exemptPurchaseCode: "EXEMPT-P",
  separateTaxAccounts: false,
  chartTerms: {
    taxOutput: "VAT",
    payrollTax: "PAYE / UIF / SDL payable",
    retirement: "Pension & provident fund contributions",
    retirementPayable: "Retirement fund contributions payable",
    musicLicensing: "SAMRO music licence",
  },
  returnForm: {
    code: "VAT201",
    name: "VAT return (VAT201)",
    authority: "SARS",
    authorityUrl: "https://www.sars.gov.za/types-of-tax/value-added-tax/vat-returns/",
    boxes: [
      box("1", "Standard-rated supplies (including VAT)", (q) => q.gross("sales", ["standard"]), { section: "Output tax" }),
      box("4", "Output tax on standard-rated supplies", (q) => q.tax("sales", ["standard"])),
      box("2", "Zero-rated supplies (excluding exports)", (q) => q.net("sales", ["zero"])),
      box("2A", "Zero-rated exported goods", (q) => q.net("sales", ["export"])),
      box("3", "Exempt and non-supplies", (q) => q.net("sales", ["exempt"])),
      box("13", "Total output tax", (q) => q.tax("sales"), { total: true }),
      box("14", "Input tax on capital goods and services", (q) => q.tax("purchases", ["capital"]), { section: "Input tax" }),
      box("15", "Input tax on other goods and services", (q) => q.tax("purchases", ["standard", "import"])),
      box("19", "Total input tax", (q) => q.box("14") + q.box("15"), { total: true }),
      box("20", "VAT payable / (refundable)", (q) => q.box("13") - q.box("19"), { total: true }),
    ],
    net: (q) => q.box("20"),
    dueDate: (periodEnd) => endOfMonthAfter(periodEnd, 1),
    notes: ["eFiling returns are due on the last business day of the month after the period; manual returns on the 25th."],
  },
  notes: [
    "Registration becomes compulsory once taxable supplies exceed SARS's threshold in any 12 months. Check the current figure on sars.gov.za.",
    "Olune Books prepares the VAT201 figures; you submit them on SARS eFiling.",
  ],
  reviewedAt: "2026-10-01",
};
