// ============================================================================
//  components/marketing/landing/privacy-data.ts — Privacy Policy copy, kept
//  out of the "use client" module for the same reason as faq-data.ts: a
//  Server Component importing a plain export from a client-boundary file
//  gets an opaque client reference back, not the real array, at build time.
// ============================================================================

import type { LegalSection } from "@/components/marketing/landing/legal-prose";

export const PRIVACY_LAST_UPDATED = "16 July 2026";
export const PRIVACY_CONTACT_EMAIL = "support@olune.co.nz";
export const PRIVACY_ADDRESS = "4 Limes Avenue, Christchurch, Parklands, 8083";

export const PRIVACY_SECTIONS: LegalSection[] = [
  {
    heading: "1. Introduction",
    paragraphs: [
      'Olune Limited ("Olune," "we," "us," or "our") provides a software-as-a-service platform for studio and club management ("Service"). This Privacy Policy explains how we collect, use, disclose, and protect personal information when you use our website, applications, and Service.',
      "We are committed to protecting your privacy and handling your personal information in accordance with the Privacy Act 2020 (New Zealand) and, where applicable to users outside New Zealand, other relevant privacy laws (such as the EU/UK General Data Protection Regulation and the Australian Privacy Act 1988).",
      "This Policy applies to two groups of people, and it's important to understand the distinction:",
    ],
    bullets: [
      'Customers — the studios, clubs, and organisations that subscribe to Olune ("Customer," "you," when we mean the subscribing organisation or its staff/administrators).',
      'End Users — the students, members, parents, or clients of our Customers, whose data Customers input into or collect through the platform ("End Users").',
    ],
  },
  {
    heading: "",
    paragraphs: [
      'Where we process End User data on behalf of a Customer, the Customer is generally the "controller" of that data and Olune acts as a "processor" or "service provider," operating under the Customer\'s instructions and our Data Processing Agreement (where one is in place). If you are an End User with questions about your data, please contact the studio or club you are a member of in the first instance, as they control what information is collected and how it is used.',
    ],
  },
  {
    heading: "2. Information We Collect",
    subsections: [
      {
        heading: "2.1 Information Customers provide to us directly",
        bullets: [
          "Account and business details: name, business name, email address, phone number, billing address.",
          "Login credentials and authentication data.",
          "Payment and billing information (processed via our third-party payment processor — we do not store full card numbers).",
          "Support requests, correspondence, and feedback.",
        ],
      },
      {
        heading: "2.2 Information Customers input about End Users",
        paragraphs: ["Depending on how a Customer configures and uses the Service, this may include:"],
        bullets: [
          "Names, contact details, and dates of birth of students/members (and, for minors, their parents or guardians).",
          "Enrolment, attendance, class, and membership records.",
          "Emergency contact and medical/allergy information, where a studio chooses to record it for safety purposes.",
          "Payment and billing records related to fees, tuition, or memberships.",
          "Photos or videos, where a studio uploads these (e.g., for marketing, portfolios, or performance records).",
        ],
      },
      {
        heading: "",
        paragraphs: [
          "Olune does not decide what End User data is collected — this is determined by each Customer. Customers are responsible for ensuring they have a lawful basis and appropriate consents to collect and share this information with us.",
        ],
      },
      {
        heading: "2.3 Information collected automatically",
        bullets: [
          "Device and usage data: IP address, browser type, operating system, pages visited, and actions taken within the Service.",
          "Cookies and similar technologies (see Section 8).",
          "Log and diagnostic data generated by our hosting and infrastructure providers.",
        ],
      },
      {
        heading: "2.4 Information from third parties",
        bullets: [
          "Payment confirmation data from our payment processor.",
          "Data from integrations a Customer chooses to connect (e.g., automation or communication tools), where the Customer has authorised the connection.",
        ],
      },
    ],
  },
  {
    heading: "3. How We Use Information",
    paragraphs: ["We use personal information to:"],
    bullets: [
      "Provide, operate, and maintain the Service, including multi-tenant account separation so each Customer's data is kept logically separate from others.",
      "Process subscription payments and manage billing.",
      "Communicate with Customers about their account, updates, and support requests.",
      "Send Service-related notifications (e.g., to End Users, where a Customer uses the platform to send class reminders or invoices).",
      "Monitor, secure, and improve the Service, including diagnosing technical issues.",
      "Comply with legal obligations and enforce our Terms of Service.",
      "With consent or as otherwise permitted by law, send marketing communications about Olune (Customers and prospective customers only — not End Users).",
    ],
  },
  {
    heading: "",
    paragraphs: ["We do not use End User data for our own marketing purposes, and we do not sell personal information."],
  },
  {
    heading: "4. Legal Basis for Processing",
    paragraphs: ["Where required (for example, for users in the UK/EU), we rely on the following legal bases:"],
    bullets: [
      "Performance of a contract — to provide the Service to Customers.",
      "Legitimate interests — to secure, maintain, and improve the Service, and for fraud prevention.",
      "Consent — for optional marketing communications and certain cookies.",
      "Legal obligation — where we must retain or disclose information to comply with the law.",
    ],
  },
  {
    heading: "5. How We Share Information",
    paragraphs: ["We share personal information only as follows:"],
    bullets: [
      "Service providers/subprocessors — companies that help us operate the Service, such as our cloud hosting and database infrastructure provider, payment processor, and automation/workflow tooling. These providers are contractually bound to protect information and use it only for the purposes we specify.",
      "Within a Customer's account — data an End User's studio collects is visible to authorised staff of that studio/Customer, as configured by the Customer.",
      "Legal and safety reasons — where required by law, regulation, legal process, or to protect the rights, property, or safety of Olune, our Customers, or others.",
      "Business transfers — if Olune is involved in a merger, acquisition, financing, or sale of assets, personal information may be transferred as part of that transaction, subject to confidentiality protections.",
    ],
  },
  {
    heading: "",
    paragraphs: ["We do not sell personal information to third parties."],
  },
  {
    heading: "6. International Data Transfers",
    paragraphs: [
      "Our infrastructure providers may store or process data outside New Zealand. Where personal information is transferred internationally, we take reasonable steps to ensure it receives a comparable standard of protection, including via contractual safeguards with our providers.",
    ],
  },
  {
    heading: "7. Data Retention",
    paragraphs: [
      "We retain personal information for as long as a Customer's account is active and as necessary to provide the Service. Following account closure, we retain data for a limited period to allow for account recovery, comply with legal or accounting obligations, and resolve disputes, after which it is securely deleted or anonymised, unless a longer retention period is required by law or requested by the Customer.",
    ],
  },
  {
    heading: "8. Cookies and Tracking Technologies",
    paragraphs: ["We use cookies and similar technologies to:"],
    bullets: [
      "Keep you logged in and maintain session security.",
      "Remember preferences and settings.",
      "Understand how the Service is used, to help us improve it.",
    ],
  },
  {
    heading: "",
    paragraphs: ["You can control cookies through your browser settings. Disabling essential cookies may affect the functionality of the Service."],
  },
  {
    heading: "9. Data Security",
    paragraphs: [
      "We implement reasonable technical and organisational measures to protect personal information, including encryption in transit, access controls, and multi-tenant data isolation. However, no method of transmission or storage is completely secure, and we cannot guarantee absolute security.",
      "If we become aware of a data breach affecting personal information, we will notify affected Customers and relevant regulators as required under the Privacy Act 2020 and other applicable law.",
    ],
  },
  {
    heading: "10. Your Rights",
    paragraphs: ["Under the Privacy Act 2020, individuals in New Zealand have the right to:"],
    bullets: [
      "Request access to personal information we (or, in the case of End User data, a Customer via us) hold about them.",
      "Request correction of inaccurate or incomplete information.",
    ],
  },
  {
    heading: "",
    paragraphs: [
      "Individuals in other jurisdictions (e.g., under the GDPR) may have additional rights, such as the right to erasure, restriction of processing, data portability, and objection to processing.",
      "If you are an End User, please contact your studio or club directly, as they control the data and can direct us to action your request. If you are a Customer, you can access and correct most information directly within your account, or contact us using the details below.",
    ],
  },
  {
    heading: "11. Children's Information",
    paragraphs: [
      "Many of our Customers are dance, sport, or activity studios that manage information about minors. Olune relies on Customers (as the data controllers) to obtain appropriate parental/guardian consent before entering a child's information into the Service. We do not knowingly collect information directly from children without a Customer's involvement.",
    ],
  },
  {
    heading: "12. Third-Party Links and Integrations",
    paragraphs: [
      "The Service may contain links to third-party websites or allow Customers to connect third-party integrations. We are not responsible for the privacy practices of these third parties, and we encourage you to review their privacy policies.",
    ],
  },
  {
    heading: "13. Changes to This Policy",
    paragraphs: [
      'We may update this Privacy Policy from time to time. Material changes will be notified to Customers via email or in-app notice. The "Last updated" date at the top of this Policy indicates when it was last revised.',
    ],
  },
];
