// ============================================================================
//  lib/seo.ts — canonical URL + structured-data helpers shared by every
//  metadata/robots/sitemap entry point. Multi-tenant, so nothing here is
//  static: origin is always derived from the incoming request host.
// ============================================================================

import { canonicalAppUrl } from "@/lib/app-url";
import { CURRENCY_CODE } from "@/lib/currency";

const ROOT_DOMAIN = process.env.NEXT_PUBLIC_ROOT_DOMAIN ?? "olune.app";

/**
 * The origin Olune-brand pages actually serve a 200 on — the one URL Google
 * should index. Deliberately NOT derived from ROOT_DOMAIN: in production the
 * apex (olune.co.nz) 308-redirects to www, and a canonical pointing at a
 * redirect is a canonical Google has to second-guess.
 *
 * Delegates to canonicalAppUrl() rather than reading NEXT_PUBLIC_APP_URL
 * directly: that env var is operator-set and has been deployed as a bare host
 * ("olune.co.nz", no scheme). Used verbatim it makes `new URL()` throw, and
 * because the root layout's metadataBase is built from this value, that took
 * down every route in the app. canonicalAppUrl() supplies the missing scheme
 * and applies the same apex -> www rule OAuth callbacks already rely on.
 */
export const CANONICAL_ORIGIN = canonicalAppUrl();

/**
 * Absolute URL on the canonical marketing origin, ignoring the request host.
 *
 * Olune-brand pages (/faq, /team, /privacy…) are served on every studio
 * subdomain and custom domain too, so their canonical has to point at the one
 * authoritative copy rather than at whatever host the request arrived on.
 */
export function rootUrl(path = "/"): string {
  return `${CANONICAL_ORIGIN}${path === "/" ? "" : path}`;
}

/** Absolute origin (protocol + host) for the incoming request host header. */
export function originForHost(host: string | null): string {
  if (!host) return `https://${ROOT_DOMAIN}`;
  const hostname = host.split(":")[0];
  const isLocal = hostname === "localhost" || hostname.endsWith(".localhost");
  return `${isLocal ? "http" : "https"}://${host}`;
}

/** JSON-LD SoftwareApplication schema for the root Olune marketing site. */
export function organizationJsonLd(origin: string) {
  return {
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    name: "Olune",
    url: origin,
    applicationCategory: "BusinessApplication",
    operatingSystem: "Web",
    // Must stay in sync with meta.description in messages/*/core.json —
    // structured data that contradicts the rendered page gets discarded.
    description:
      "Olune runs the admin side of a dance or fitness studio — enrolments, timetables, invoicing and payments, and a live client website you edit yourself.",
    // Must match the entry-tier price rendered in the pricing section — Google
    // rejects structured data that contradicts the visible page.
    offers: {
      "@type": "Offer",
      price: "19",
      priceCurrency: CURRENCY_CODE,
    },
  } as const;
}

/**
 * JSON-LD WebSite schema — Google's documented input for the site name it
 * prints above the blue link on a homepage result. Without it Google guesses
 * from the <title>, the H1 and the domain, and a long marketing title tends to
 * get collapsed to something arbitrary. Emit on the root marketing homepage
 * only: Google ignores WebSite markup found on inner pages.
 */
export function websiteJsonLd(origin: string) {
  return {
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: "Olune",
    alternateName: "Olune Studio Management",
    url: origin,
  } as const;
}

/** JSON-LD Organization schema — names the entity and supplies the mark Google
 *  shows beside the domain in a result. */
export function organizationEntityJsonLd(origin: string) {
  return {
    "@context": "https://schema.org",
    "@type": "Organization",
    name: "Olune",
    url: origin,
    logo: `${origin}/icon.svg`,
    description:
      "Studio management software for dance, fitness and performing-arts studios — enrolments, timetabling, invoicing and a live client website in one place.",
  } as const;
}

/**
 * JSON-LD SiteNavigationElement list — the machine-readable version of the
 * site's primary navigation. Sitelinks (the indented sub-page list under a
 * homepage result) are generated by Google, never requested; what this does is
 * give it an unambiguous statement of which pages *are* the top-level ones, so
 * it isn't inferring structure from a footer link soup.
 */
export function siteNavigationJsonLd(
  origin: string,
  items: { name: string; path: string; description: string }[],
) {
  return {
    "@context": "https://schema.org",
    "@type": "ItemList",
    itemListElement: items.map((item, i) => ({
      "@type": "SiteNavigationElement",
      position: i + 1,
      name: item.name,
      description: item.description,
      url: `${origin}${item.path}`,
    })),
  } as const;
}

/** JSON-LD LocalBusiness (ExerciseGym) schema for a studio's public site. */
export function studioLocalBusinessJsonLd(params: {
  origin: string;
  studioName: string;
  tagline?: string | null;
  logoUrl?: string | null;
  contactEmail?: string;
  contactPhone?: string;
  regionLabel?: string;
}) {
  const { origin, studioName, tagline, logoUrl, contactEmail, contactPhone, regionLabel } = params;
  return {
    "@context": "https://schema.org",
    "@type": "ExerciseGym",
    name: studioName,
    url: origin,
    ...(logoUrl ? { logo: logoUrl, image: logoUrl } : {}),
    ...(tagline ? { description: tagline } : {}),
    ...(contactEmail ? { email: contactEmail } : {}),
    ...(contactPhone ? { telephone: contactPhone } : {}),
    ...(regionLabel
      ? { address: { "@type": "PostalAddress", addressLocality: regionLabel } }
      : {}),
  } as const;
}

/** JSON-LD FAQPage schema — feeds Google's FAQ rich-result snippet. */
export function faqPageJsonLd(items: { q: string; a: string }[]) {
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: items.map(({ q, a }) => ({
      "@type": "Question",
      name: q,
      acceptedAnswer: { "@type": "Answer", text: a },
    })),
  } as const;
}

/** JSON-LD Person schema for a public instructor profile or team bio page. */
export function personJsonLd(params: {
  /** Canonical URL of the page describing this person. */
  url: string;
  name: string;
  jobTitle?: string | null;
  description?: string | null;
  image?: string | null;
  /** City or region the person teaches in. */
  areaServed?: string | null;
  /** Disciplines, certifications — anything they're credentialed in. */
  knowsAbout?: string[];
  worksFor?: { name: string; url: string } | null;
}) {
  const { url, name, jobTitle, description, image, areaServed, knowsAbout, worksFor } = params;
  return {
    "@context": "https://schema.org",
    "@type": "Person",
    name,
    url,
    ...(jobTitle ? { jobTitle } : {}),
    ...(description ? { description } : {}),
    ...(image ? { image } : {}),
    ...(areaServed ? { areaServed } : {}),
    ...(knowsAbout?.length ? { knowsAbout } : {}),
    ...(worksFor
      ? { worksFor: { "@type": "Organization", name: worksFor.name, url: worksFor.url } }
      : {}),
  } as const;
}

/**
 * JSON-LD Article schema for an editorial page (/guides, /compare).
 *
 * Publisher is the Olune organisation rather than a named author: these are
 * product-team pages, and claiming a byline Google can't corroborate anywhere
 * else is worse than claiming none.
 */
export function articleJsonLd(params: {
  url: string;
  headline: string;
  description: string;
  /** ISO date — surfaces as the freshness signal on the result. */
  dateModified: string;
}) {
  const { url, headline, description, dateModified } = params;
  return {
    "@context": "https://schema.org",
    "@type": "Article",
    mainEntityOfPage: { "@type": "WebPage", "@id": url },
    headline,
    description,
    dateModified,
    datePublished: dateModified,
    publisher: {
      "@type": "Organization",
      name: "Olune",
      url: CANONICAL_ORIGIN,
    },
  } as const;
}

/**
 * JSON-LD BreadcrumbList. Google prints these above the blue link in place of
 * the raw URL, so a nested page reads as "olune.co.nz › Guides › …" rather
 * than a slug. Pass the trail in order, excluding the site root.
 */
export function breadcrumbJsonLd(trail: { name: string; path: string }[]) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [{ name: "Olune", path: "/" }, ...trail].map((item, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: item.name,
      item: rootUrl(item.path),
    })),
  } as const;
}

/** JSON-LD ItemList for an index page, so the collection reads as a set. */
export function itemListJsonLd(items: { name: string; path: string }[]) {
  return {
    "@context": "https://schema.org",
    "@type": "ItemList",
    itemListElement: items.map((item, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: item.name,
      url: rootUrl(item.path),
    })),
  } as const;
}

/**
 * JSON-LD Product + Offer list for the pricing page. Prices must match the
 * rendered table exactly — Google drops offer markup that contradicts the
 * visible page, and this is the one page where it definitely checks.
 */
export function pricingJsonLd(plans: { name: string; price: string; desc: string }[]) {
  return {
    "@context": "https://schema.org",
    "@type": "Product",
    name: "Olune",
    description:
      "Studio management software for dance and fitness studios — enrolments, timetables, attendance, term fees and a live studio website.",
    brand: { "@type": "Brand", name: "Olune" },
    offers: plans.map((p) => ({
      "@type": "Offer",
      name: p.name,
      description: p.desc,
      price: p.price,
      priceCurrency: CURRENCY_CODE,
      url: rootUrl("/pricing"),
      availability: "https://schema.org/InStock",
    })),
  } as const;
}
